[package]
authors = ["Reza Hajianpour <hajianpour.mr@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ast"
version = "0.1.0"

[dependencies]
syntax = {path = "../syntax"}
text-size = "1.1.0"

[dev-dependencies]
parser = {path = "../parser"}
