[package]
authors = ["Reza Hajianpour <hajianpour.mr@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "syntax"
version = "0.1.0"

[dependencies]
lexer = {path = "../lexer"}
num-derive = "0.3.3"
num-traits = "0.2.14"
rowan = "0.12.1"
